services:
  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - mediawiki-html:/var/www/${MEDIAWIKI_HOST}/html/w
      - ./mediawiki-private-extension:/var/www/${MEDIAWIKI_HOST}/html/w/extensions/private
    environment:
      - MEDIAWIKI_HOST=${MEDIAWIKI_HOST}
    depends_on:
      mediawiki-html:
        condition: service_completed_successfully
      mariadb:
        condition: service_started
      php-fpm:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 5s
      retries: 3
  mediawiki-html:
    build: mediawiki-html
    volumes:
      - mediawiki-html:/mediawiki
    environment:
      - MEDIAWIKI_HOST=${MEDIAWIKI_HOST}
      - MEDIAWIKI_TARBALL_URL=${MEDIAWIKI_TARBALL_URL}
      - MEDIAWIKI_ADMIN_PASS=${MEDIAWIKI_ADMIN_PASS}
      - MEDIAWIKI_DB_USER=${MEDIAWIKI_DB_USER}
      - MEDIAWIKI_DB_PASS=${MEDIAWIKI_DB_PASS}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MEDIAWIKI_SCRIPT_PATH=${MEDIAWIKI_SCRIPT_PATH}
      - MEDIAWIKI_WIKI_NAME=${MEDIAWIKI_WIKI_NAME}
      - MEDIAWIKI_ADMIN_USER=${MEDIAWIKI_ADMIN_USER}
    depends_on:
      mariadb:
        condition: service_healthy
  php-fpm:
    build: php-fpm
    image: 283124aa-c663-4ec0-900d-82cab0ab7c29
    volumes:
      - mediawiki-html:/var/www/${MEDIAWIKI_HOST}/html/w
      - ./mediawiki-private-extension:/var/www/${MEDIAWIKI_HOST}/html/w/extensions/private
    # User and group id
    #
    # Since 1.17.0, both alpine- and debian-based images variants use
    # the same user and group ids to drop the privileges for worker
    # processes.
    #
    # $ id
    # uid=101(nginx) gid=101(nginx) groups=101(nginx)
    #
    # Source: https://hub.docker.com/_/nginx
    user: 101:101
  mariadb:
    build: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 5s
      retries: 3

volumes:
  mariadb:
  mediawiki-html:
