services:
  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - mediawiki-html:/var/www/${MEDIAWIKI_HOST}/html
    environment:
      - MEDIAWIKI_HOST=${MEDIAWIKI_HOST}
    depends_on:
      mediawiki-html:
        condition: service_completed_successfully
      mariadb:
        condition: service_started
      php-fpm:
        condition: service_started
  mediawiki-html:
    build: mediawiki-html
    volumes:
      - mediawiki-html:/var/www/${MEDIAWIKI_HOST}/html
    environment:
      - MEDIAWIKI_HOST=${MEDIAWIKI_HOST}
  php-fpm:
    build: php-fpm
    volumes:
      - mediawiki-html:/var/www/${MEDIAWIKI_HOST}/html
  mariadb:
    build: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
  mediawiki-html:
