services:
  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - mediawiki-html:/var/www/${MEDIAWIKI_HOST}/html/w
      - ./mediawiki-private-extension:/var/www/${MEDIAWIKI_HOST}/html/w/extensions/private
    environment:
      - MEDIAWIKI_HOST=${MEDIAWIKI_HOST}
    depends_on:
      mediawiki-html:
        condition: service_completed_successfully
      mariadb:
        condition: service_started
      php-fpm:
        condition: service_started
  mediawiki-html:
    build: mediawiki-html
    volumes:
      - mediawiki-html:/var/www/${MEDIAWIKI_HOST}/html/w
    environment:
      - MEDIAWIKI_HOST=${MEDIAWIKI_HOST}
      - MEDIAWIKI_TARBALL_URL=${MEDIAWIKI_TARBALL_URL}
  php-fpm:
    build: php-fpm
    volumes:
      - mediawiki-html:/var/www/${MEDIAWIKI_HOST}/html/w
      - ./mediawiki-private-extension:/var/www/${MEDIAWIKI_HOST}/html/w/extensions/private
    # User and group id
    #
    # Since 1.17.0, both alpine- and debian-based images variants use
    # the same user and group ids to drop the privileges for worker
    # processes.
    #
    # $ id
    # uid=101(nginx) gid=101(nginx) groups=101(nginx)
    #
    # Source: https://hub.docker.com/_/nginx
    user: 101:101
  mariadb:
    build: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
  mediawiki-html:
