services:
  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - mediawiki-app:/var/www/${MEDIAWIKI_HOST}/html/w
      - mediawiki-private:/var/www/${MEDIAWIKI_HOST}/html/w/private
      - mediawiki-public:/var/www/${MEDIAWIKI_HOST}/html/w/public
    environment:
      - MEDIAWIKI_HOST=${MEDIAWIKI_HOST}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 5s
      retries: 3
  mediawiki-app:
    build:
      context: mediawiki-app
      args:
        MEDIAWIKI_TARBALL_URL: ${MEDIAWIKI_TARBALL_URL}
    volumes:
      - mediawiki-app:/mediawiki
  php-fpm:
    build:
      context: php-fpm
      args:
        MEDIAWIKI_HOST: ${MEDIAWIKI_HOST}
    volumes:
      - mediawiki-app:/var/www/${MEDIAWIKI_HOST}/html/w
      - mediawiki-private:/var/www/${MEDIAWIKI_HOST}/html/w/private
      - mediawiki-public:/var/www/${MEDIAWIKI_HOST}/html/w/public
    # User and group id
    #
    # Since 1.17.0, both alpine- and debian-based images variants use
    # the same user and group ids to drop the privileges for worker
    # processes.
    #
    # $ id
    # uid=101(nginx) gid=101(nginx) groups=101(nginx)
    #
    # Source: https://hub.docker.com/_/nginx
    user: 101:101
  mariadb:
    build: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 5s
      interval: 1m
      timeout: 5s
      retries: 3
  git:
    build: git
    ports:
      - 8022:22
    volumes:
      - git-ssh-configuration:/home/git/.ssh
      - git-repositories:/opt/git
      - mediawiki-public:/mediawiki-public-settings

volumes:
  mariadb:
  mediawiki-app:
  mediawiki-private:
  mediawiki-public:
  git-ssh-configuration:
  git-repositories:
